use once_cell::sync::Lazy;

// Our dictionary of languages
#[derive(Debug, Clone, Default)]
pub struct Language {
    pub name: String,
    pub code: String
}

pub static LANGUAGES: Lazy<Vec<Language>> = Lazy::new(|| vec![
    // auto
    Language { code: "auto".into(), name: "Automatic".into() },

    // codes
    Language { code: "af".into(), name: "Afrikaans".into() },
    Language { code: "sq".into(), name: "Albanian".into() },
    Language { code: "am".into(), name: "Amharic".into() },
    Language { code: "ar".into(), name: "Arabic".into() },
    Language { code: "hy".into(), name: "Armenian".into() },
    Language { code: "as".into(), name: "Assamese".into() },
    Language { code: "ay".into(), name: "Aymara".into() },
    Language { code: "az".into(), name: "Azerbaijani".into() },
    Language { code: "bm".into(), name: "Bambara".into() },
    Language { code: "eu".into(), name: "Basque".into() },
    Language { code: "be".into(), name: "Belarusian".into() },
    Language { code: "bn".into(), name: "Bengali".into() },
    Language { code: "bho".into(), name: "Bhojpuri".into() },
    Language { code: "bs".into(), name: "Bosnian".into() },
    Language { code: "bg".into(), name: "Bulgarian".into() },
    Language { code: "ca".into(), name: "Catalan".into() },
    Language { code: "ceb".into(), name: "Cebuano".into() },
    Language { code: "ny".into(), name: "Chichewa".into() },
    Language { code: "zh-CN".into(), name: "Chinese (Simplified)".into() },
    Language { code: "zh-TW".into(), name: "Chinese (Traditional)".into() },
    Language { code: "co".into(), name: "Corsican".into() },
    Language { code: "hr".into(), name: "Croatian".into() },
    Language { code: "cs".into(), name: "Czech".into() },
    Language { code: "da".into(), name: "Danish".into() },
    Language { code: "dv".into(), name: "Dhivehi".into() },
    Language { code: "doi".into(), name: "Dogri".into() },
    Language { code: "nl".into(), name: "Dutch".into() },
    Language { code: "en".into(), name: "English".into() },
    Language { code: "eo".into(), name: "Esperanto".into() },
    Language { code: "et".into(), name: "Estonian".into() },
    Language { code: "ee".into(), name: "Ewe".into() },
    Language { code: "tl".into(), name: "Filipino".into() },
    Language { code: "fi".into(), name: "Finnish".into() },
    Language { code: "fr".into(), name: "French".into() },
    Language { code: "fy".into(), name: "Frisian".into() },
    Language { code: "gl".into(), name: "Galician".into() },
    Language { code: "ka".into(), name: "Georgian".into() },
    Language { code: "de".into(), name: "German".into() },
    Language { code: "el".into(), name: "Greek".into() },
    Language { code: "gn".into(), name: "Guarani".into() },
    Language { code: "gu".into(), name: "Gujarati".into() },
    Language { code: "ht".into(), name: "Haitian Creole".into() },
    Language { code: "ha".into(), name: "Hausa".into() },
    Language { code: "haw".into(), name: "Hawaiian".into() },
    Language { code: "iw".into(), name: "Hebrew".into() },
    Language { code: "he".into(), name: "Hebrew".into() },
    Language { code: "hi".into(), name: "Hindi".into() },
    Language { code: "hmn".into(), name: "Hmong".into() },
    Language { code: "hu".into(), name: "Hungarian".into() },
    Language { code: "is".into(), name: "Icelandic".into() },
    Language { code: "ig".into(), name: "Igbo".into() },
    Language { code: "ilo".into(), name: "Ilocano".into() },
    Language { code: "id".into(), name: "Indonesian".into() },
    Language { code: "ga".into(), name: "Irish".into() },
    Language { code: "it".into(), name: "Italian".into() },
    Language { code: "ja".into(), name: "Japanese".into() },
    Language { code: "jw".into(), name: "Javanese".into() },
    Language { code: "kn".into(), name: "Kannada".into() },
    Language { code: "kk".into(), name: "Kazakh".into() },
    Language { code: "km".into(), name: "Khmer".into() },
    Language { code: "rw".into(), name: "Kinyarwanda".into() },
    Language { code: "gom".into(), name: "Konkani".into() },
    Language { code: "ko".into(), name: "Korean".into() },
    Language { code: "kri".into(), name: "Krio".into() },
    Language { code: "ku".into(), name: "Kurdish (Kurmanji)".into() },
    Language { code: "ckb".into(), name: "Kurdish (Sorani)".into() },
    Language { code: "ky".into(), name: "Kyrgyz".into() },
    Language { code: "lo".into(), name: "Lao".into() },
    Language { code: "la".into(), name: "Latin".into() },
    Language { code: "lv".into(), name: "Latvian".into() },
    Language { code: "ln".into(), name: "Lingala".into() },
    Language { code: "lt".into(), name: "Lithuanian".into() },
    Language { code: "lg".into(), name: "Luganda".into() },
    Language { code: "lb".into(), name: "Luxembourgish".into() },
    Language { code: "mk".into(), name: "Macedonian".into() },
    Language { code: "mai".into(), name: "Maithili".into() },
    Language { code: "mg".into(), name: "Malagasy".into() },
    Language { code: "ms".into(), name: "Malay".into() },
    Language { code: "ml".into(), name: "Malayalam".into() },
    Language { code: "mt".into(), name: "Maltese".into() },
    Language { code: "mi".into(), name: "Maori".into() },
    Language { code: "mr".into(), name: "Marathi".into() },
    Language { code: "mni-Mtei".into(), name: "Meiteilon (Manipuri)".into() },
    Language { code: "lus".into(), name: "Mizo".into() },
    Language { code: "mn".into(), name: "Mongolian".into() },
    Language { code: "my".into(), name: "Myanmar (Burmese)".into() },
    Language { code: "ne".into(), name: "Nepali".into() },
    Language { code: "no".into(), name: "Norwegian".into() },
    Language { code: "or".into(), name: "Odia (Oriya)".into() },
    Language { code: "om".into(), name: "Oromo".into() },
    Language { code: "ps".into(), name: "Pashto".into() },
    Language { code: "fa".into(), name: "Persian".into() },
    Language { code: "pl".into(), name: "Polish".into() },
    Language { code: "pt".into(), name: "Portuguese".into() },
    Language { code: "pa".into(), name: "Punjabi".into() },
    Language { code: "qu".into(), name: "Quechua".into() },
    Language { code: "ro".into(), name: "Romanian".into() },
    Language { code: "ru".into(), name: "Russian".into() },
    Language { code: "sm".into(), name: "Samoan".into() },
    Language { code: "sa".into(), name: "Sanskrit".into() },
    Language { code: "gd".into(), name: "Scots Gaelic".into() },
    Language { code: "nso".into(), name: "Sepedi".into() },
    Language { code: "sr".into(), name: "Serbian".into() },
    Language { code: "st".into(), name: "Sesotho".into() },
    Language { code: "sn".into(), name: "Shona".into() },
    Language { code: "sd".into(), name: "Sindhi".into() },
    Language { code: "si".into(), name: "Sinhala".into() },
    Language { code: "sk".into(), name: "Slovak".into() },
    Language { code: "sl".into(), name: "Slovenian".into() },
    Language { code: "so".into(), name: "Somali".into() },
    Language { code: "es".into(), name: "Spanish".into() },
    Language { code: "su".into(), name: "Sundanese".into() },
    Language { code: "sw".into(), name: "Swahili".into() },
    Language { code: "sv".into(), name: "Swedish".into() },
    Language { code: "tg".into(), name: "Tajik".into() },
    Language { code: "ta".into(), name: "Tamil".into() },
    Language { code: "tt".into(), name: "Tatar".into() },
    Language { code: "te".into(), name: "Telugu".into() },
    Language { code: "th".into(), name: "Thai".into() },
    Language { code: "ti".into(), name: "Tigrinya".into() },
    Language { code: "ts".into(), name: "Tsonga".into() },
    Language { code: "tr".into(), name: "Turkish".into() },
    Language { code: "tk".into(), name: "Turkmen".into() },
    Language { code: "ak".into(), name: "Twi".into() },
    Language { code: "uk".into(), name: "Ukrainian".into() },
    Language { code: "ur".into(), name: "Urdu".into() },
    Language { code: "ug".into(), name: "Uyghur".into() },
    Language { code: "uz".into(), name: "Uzbek".into() },
    Language { code: "vi".into(), name: "Vietnamese".into() },
    Language { code: "cy".into(), name: "Welsh".into() },
    Language { code: "xh".into(), name: "Xhosa".into() },
    Language { code: "yi".into(), name: "Yiddish".into() },
    Language { code: "yo".into(), name: "Yoruba".into() },
    Language { code: "zu".into(), name: "Zulu".into() }
]);

pub fn get_by_name(name: &str) -> Option<Language> {
    LANGUAGES.iter()
        .find(|lang| lang.name.eq_ignore_ascii_case(name))
        .cloned()
}

pub fn get_language_name(code: &str) -> Option<String> {
    LANGUAGES.iter()
        .find(|lang| lang.code == code)
        .map(|lang| lang.name.clone())
}

pub fn get_language_code(name: &str) -> Option<String> {
    LANGUAGES.iter()
        .find(|lang| lang.name.eq_ignore_ascii_case(name))
        .map(|lang| lang.code.clone())
}
