// This code was autogenerated with `dbus-codegen-rust --crossroads -s -d org.freedesktop.NetworkManager -p /org/freedesktop/NetworkManager/AccessPoint/1810`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus_crossroads as crossroads;

pub trait OrgFreedesktopDBusProperties {
    fn get(&mut self, interface_name: String, property_name: String) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::MethodErr>;
    fn get_all(&mut self, interface_name: String) -> Result<arg::PropMap, dbus::MethodErr>;
    fn set(&mut self, interface_name: String, property_name: String, value: arg::Variant<Box<dyn arg::RefArg + 'static>>) -> Result<(), dbus::MethodErr>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

pub fn register_org_freedesktop_dbus_properties<T>(cr: &mut crossroads::Crossroads) -> crossroads::IfaceToken<T>
where T: OrgFreedesktopDBusProperties + Send + 'static
{
    cr.register("org.freedesktop.DBus.Properties", |b| {
        b.signal::<(String,arg::PropMap,Vec<String>,), _>("PropertiesChanged", ("interface_name","changed_properties","invalidated_properties",));
        b.method("Get", ("interface_name","property_name",), ("value",), |_, t: &mut T, (interface_name,property_name,)| {
            t.get(interface_name,property_name,)
                .map(|x| (x,))
        });
        b.method("GetAll", ("interface_name",), ("properties",), |_, t: &mut T, (interface_name,)| {
            t.get_all(interface_name,)
                .map(|x| (x,))
        });
        b.method("Set", ("interface_name","property_name","value",), (), |_, t: &mut T, (interface_name,property_name,value,)| {
            t.set(interface_name,property_name,value,)
        });
    })
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&mut self) -> Result<String, dbus::MethodErr>;
}

pub fn register_org_freedesktop_dbus_introspectable<T>(cr: &mut crossroads::Crossroads) -> crossroads::IfaceToken<T>
where T: OrgFreedesktopDBusIntrospectable + Send + 'static
{
    cr.register("org.freedesktop.DBus.Introspectable", |b| {
        b.method("Introspect", (), ("xml_data",), |_, t: &mut T, ()| {
            t.introspect()
                .map(|x| (x,))
        });
    })
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&mut self) -> Result<(), dbus::MethodErr>;
    fn get_machine_id(&mut self) -> Result<String, dbus::MethodErr>;
}

pub fn register_org_freedesktop_dbus_peer<T>(cr: &mut crossroads::Crossroads) -> crossroads::IfaceToken<T>
where T: OrgFreedesktopDBusPeer + Send + 'static
{
    cr.register("org.freedesktop.DBus.Peer", |b| {
        b.method("Ping", (), (), |_, t: &mut T, ()| {
            t.ping()
        });
        b.method("GetMachineId", (), ("machine_uuid",), |_, t: &mut T, ()| {
            t.get_machine_id()
                .map(|x| (x,))
        });
    })
}

pub trait OrgFreedesktopNetworkManagerAccessPoint {
    fn flags(&self) -> Result<u32, dbus::MethodErr>;
    fn wpa_flags(&self) -> Result<u32, dbus::MethodErr>;
    fn rsn_flags(&self) -> Result<u32, dbus::MethodErr>;
    fn ssid(&self) -> Result<Vec<u8>, dbus::MethodErr>;
    fn frequency(&self) -> Result<u32, dbus::MethodErr>;
    fn hw_address(&self) -> Result<String, dbus::MethodErr>;
    fn mode(&self) -> Result<u32, dbus::MethodErr>;
    fn max_bitrate(&self) -> Result<u32, dbus::MethodErr>;
    fn bandwidth(&self) -> Result<u32, dbus::MethodErr>;
    fn strength(&self) -> Result<u8, dbus::MethodErr>;
    fn last_seen(&self) -> Result<i32, dbus::MethodErr>;
}

pub fn register_org_freedesktop_network_manager_access_point<T>(cr: &mut crossroads::Crossroads) -> crossroads::IfaceToken<T>
where T: OrgFreedesktopNetworkManagerAccessPoint + Send + 'static
{
    cr.register("org.freedesktop.NetworkManager.AccessPoint", |b| {
        b.property::<u32, _>("Flags")
            .get(|_, t: &mut T| t.flags());
        b.property::<u32, _>("WpaFlags")
            .get(|_, t: &mut T| t.wpa_flags());
        b.property::<u32, _>("RsnFlags")
            .get(|_, t: &mut T| t.rsn_flags());
        b.property::<Vec<u8>, _>("Ssid")
            .get(|_, t: &mut T| t.ssid());
        b.property::<u32, _>("Frequency")
            .get(|_, t: &mut T| t.frequency());
        b.property::<String, _>("HwAddress")
            .get(|_, t: &mut T| t.hw_address());
        b.property::<u32, _>("Mode")
            .get(|_, t: &mut T| t.mode());
        b.property::<u32, _>("MaxBitrate")
            .get(|_, t: &mut T| t.max_bitrate());
        b.property::<u32, _>("Bandwidth")
            .get(|_, t: &mut T| t.bandwidth());
        b.property::<u8, _>("Strength")
            .get(|_, t: &mut T| t.strength());
        b.property::<i32, _>("LastSeen")
            .get(|_, t: &mut T| t.last_seen());
    })
}
